export const STAMP_OPTIONS = [
  '+0',
  '+1',
  '+2',
  '+3',
  '+4',
  '+5',
  '+6',
  '+7',
  '+8',
  '+9',
  '+10',
  '-1',
  '-2',
  '-3',
  '-4',
  '-5',
  '916 BIS Hallmark',
  '750 Hallmark',
  '22K Gold Stamp',
  '18K Gold Stamp',
  'Silver 925 Stamp',
  '950 Platinum Stamp',
];

export const STONE_SIZE_OPTIONS = [
  '0.01 - 0.05 ct (1.0 - 2.0 mm)',
  '0.06 - 0.10 ct (2.1 - 3.0 mm)',
  '0.11 - 0.25 ct (3.1 - 4.0 mm)',
  '0.26 - 0.50 ct (4.1 - 5.0 mm)',
  '0.51 - 1.00 ct (5.1 - 6.5 mm)',
  '1.00+ ct (Pointer / Solitaire)',
  'Custom Size',
];

export const STONE_COLOR_OPTIONS = [
  'D-E-F (Colorless Diamond)',
  'G-H (Near Colorless Diamond)',
  'I-J (Slight Yellow Diamond)',
  'Fancy Yellow',
  'Ruby Red',
  'Emerald Green',
  'Sapphire Blue',
  'Rose Pink',
  'Navratna Multi-color',
  'Black Diamond',
  'Moissanite / CZ White',
  'Custom Colour',
];
